In [1]:
import torch
import numpy as np
import torch.nn as nn

In [2]:
def cross_entropy(actual,predicted):
    loss = -np.sum(actual * np.log(predicted))
    return loss     #/float(predicted.shape[0])  -->this could have been used for normalization


In [3]:
# y must be one hot encoded
# if class 0 : [1 0 0]
# if class 1 : [0 1 0]
# if class 2 : [0 0 1]

Y = np.array([1,0,0])



In [4]:
# y_pred has possibilities

Y_pred_good = np.array([0.7,0.2,0.1])
Y_pred_bad = np.array([0.1,0.3,0.6])

l1 = cross_entropy(Y,Y_pred_good)
l2 = cross_entropy(Y,Y_pred_bad)

print(f'Loss1 numpy: {l1:.4f}')  #low loss
print(f'Loss2 numpy: {l2:.4f}')   #high loss

Loss1 numpy: 0.3567
Loss2 numpy: 2.3026


### Implementing above thing using PyTorch

In [5]:
loss = nn.CrossEntropyLoss()

In [7]:
#actual labels
#only taking correct label not One Hot Encoded
Y = torch.tensor([0])  #possible class

In [8]:
#n_samples X n_classes = 1X3
Y_pred_good = torch.tensor([[2.0,1.0,0.1]])   #--> more probability for 0
Y_pred_bad = torch.tensor([[0.5,2.0,0.3]])   #--> more probability for 1

In [9]:
l1 = loss(Y_pred_good,Y)
l2 = loss(Y_pred_bad,Y)

In [10]:
print(l1.item())   #low CE loss
print(l2.item())   #high CE loss

0.4170299470424652
1.840616226196289


### Getting actual predictions

In [11]:
_,predictions1 = torch.max(Y_pred_good,1)
_,predictions2 = torch.max(Y_pred_bad,1)

print(predictions1)
print(predictions2)

tensor([0])
tensor([1])


Multiple possible classes or samples  # 3

In [13]:
Y = torch.tensor([2,0,1])  # --> index of most probable class

In [14]:
#n_samples X n_classes = 3X3
Y_pred_good = torch.tensor([[0.1,1.0,2.1],[2.0,1.0,0.1],[0.1,3.0,0.1]])  
Y_pred_bad = torch.tensor([[2.1,1.0,0.1],[0.1,1.0,2.1],[0.1,3.0,0.1]])  
 

In [15]:
l1 = loss(Y_pred_good,Y)
l2 = loss(Y_pred_bad,Y)

In [16]:
print(l1.item())   #low CE loss
print(l2.item())

0.3018244206905365
1.6241613626480103


In [17]:
_,predictions1 = torch.max(Y_pred_good,1)
_,predictions2 = torch.max(Y_pred_bad,1)

print(predictions1)
print(predictions2)


tensor([2, 0, 1])
tensor([0, 2, 1])
