In [1]:
import torch

### Empty tensors

In [2]:
x = torch.empty(1)
y = torch.empty(3)
z = torch.empty(3,2,2)

In [3]:
x

tensor([-9.5212e-17])

In [4]:
y

tensor([0., 0., 0.])

In [5]:
z

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

### Random element tensor

In [6]:
torch.rand(2,2)

tensor([[0.1275, 0.3882],
        [0.6395, 0.7232]])

### Zeros tensor


In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### Ones tensor

In [11]:
torch.ones(2,3,dtype=torch.int)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

### Datatype

In [13]:
print(x.dtype)

torch.float32


### Size of tensor

In [15]:
print(x.size())

torch.Size([1])


### explicit tensor creation

In [16]:
x = torch.tensor([2.5 ,5.8])
print(x)

tensor([2.5000, 5.8000])


### arithmetic operations

In [18]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x,y)
z = x+ y
print(z)
k = torch.add(x, y)
print(k)

tensor([[0.3978, 0.5166],
        [0.3024, 0.5738]]) tensor([[0.1918, 0.9664],
        [0.2839, 0.0510]])
tensor([[0.5896, 1.4829],
        [0.5864, 0.6248]])
tensor([[0.5896, 1.4829],
        [0.5864, 0.6248]])


All functions in PyTorch with underscore will do inplace operation


In [19]:
y.add_(x)
y

tensor([[0.5896, 1.4829],
        [0.5864, 0.6248]])

In [21]:
x = torch.rand(5,3)
x

tensor([[0.8031, 0.2820, 0.4716],
        [0.6556, 0.3960, 0.4082],
        [0.0954, 0.6238, 0.4063],
        [0.4053, 0.7788, 0.2198],
        [0.4002, 0.2898, 0.6195]])

### Slicing extraction


In [24]:
print(x[:,0])
print(x[1,:])

tensor([0.8031, 0.6556, 0.0954, 0.4053, 0.4002])
tensor([0.6556, 0.3960, 0.4082])


### Getting exact data out of 1 element tensor

In [25]:
print(x[1,1].item())

0.3960418105125427


### Reshaping tensor


In [28]:
x = torch.rand(4,4)
print(x)
y = x.view(2,8)
print(y)

tensor([[0.4845, 0.8190, 0.1475, 0.8516],
        [0.0920, 0.4791, 0.0757, 0.4835],
        [0.5440, 0.9924, 0.7040, 0.1973],
        [0.3314, 0.0735, 0.0855, 0.2369]])
tensor([[0.4845, 0.8190, 0.1475, 0.8516, 0.0920, 0.4791, 0.0757, 0.4835],
        [0.5440, 0.9924, 0.7040, 0.1973, 0.3314, 0.0735, 0.0855, 0.2369]])


Not specifying one dimension while reshaping

In [29]:
y = x.view(-1,2)
print(y)

tensor([[0.4845, 0.8190],
        [0.1475, 0.8516],
        [0.0920, 0.4791],
        [0.0757, 0.4835],
        [0.5440, 0.9924],
        [0.7040, 0.1973],
        [0.3314, 0.0735],
        [0.0855, 0.2369]])


### Tensor to numpy and vice versa

In [31]:
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


If both get loaded in CPU they share same resources and so change in torch tensors will be reflected in numpy arrays

They both  point to same memory location

In [32]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [33]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [34]:
a += 1
print(a,b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [35]:
torch.cuda.is_available()

False

In [36]:
## Numpy can handle only CPU arrays

### CPU to GPU to CPU

In [37]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+ y
    z = z.to("cpu")

In [40]:
## whenever we have a variable in our model which we need to optimise later using gradients
a = torch.ones(5,requires_grad=True)
a

tensor([1., 1., 1., 1., 1.], requires_grad=True)