In [22]:
import torch


In [23]:
x = torch.randn(3,requires_grad=True)
print(x)

tensor([-0.6525,  0.3242,  0.2556], requires_grad=True)


In [24]:
y = x+2
print(y)

tensor([1.3475, 2.3242, 2.2556], grad_fn=<AddBackward0>)


In [25]:
z = y*y*2
print(z)

tensor([ 3.6315, 10.8036, 10.1752], grad_fn=<MulBackward0>)


In [26]:
# z= z.mean()
# print(z)

In case z was vector then below line was needed

In [27]:
v = torch.tensor([0.1,1.0,0.001],dtype=torch.float32)

In [28]:
z.backward(v)   # dz/dx  this will operate on scalar only   ; Vector Jacobian

In [29]:
print(x.grad)        ## not able to understand this computation

tensor([5.3900e-01, 9.2967e+00, 9.0223e-03])


### Detaching Gradient from a var

In [30]:
#1st way

x = torch.randn(3,requires_grad=True)
print(x)

x.requires_grad_(False)
print(x)

tensor([-0.3913, -0.4135,  1.7321], requires_grad=True)
tensor([-0.3913, -0.4135,  1.7321])


In [31]:
#2nd way

x = torch.randn(3,requires_grad=True)
print(x)

y = x.detach()
print(y)

tensor([-0.0587,  0.8131,  0.2376], requires_grad=True)
tensor([-0.0587,  0.8131,  0.2376])


In [32]:
#3rd way

x = torch.randn(3,requires_grad=True)
print(x)

with torch.no_grad():
    y = x+ 2
    print (y)

tensor([-0.7368, -1.9774,  1.2323], requires_grad=True)
tensor([1.2632, 0.0226, 3.2323])


### Everytime backward() is called gradient is accumulated

In [33]:
weights = torch.ones(4,requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    # to avoid accumulating below line is necessary and get correct gradient
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [34]:
weights = torch.ones(4,requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    # to avoid accumulating below line is necessary and get correct gradient
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
